swagger: '2.0'

info:
  version: "0.0.1"
  title: geolog api

consumes:
  - application/json
produces:
  - application/json

paths:
  /tracks:
    post:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:772663561820:function:geolog/invocations
        httpMethod: POST
      description: Create a track
      responses:
        "202":
          description: Response redirecting client to job
          headers:
            location:
              description: The location of the job to query for progress of the creation of the track
              type: string

  /tracks/{id}:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:772663561820:function:geolog/invocations
        httpMethod: POST
      description: Get a track
      parameters:
        - in: path
          name: id
          description: ID of the track
          required: true
          type: string
          format: string
      responses:
        200:
          description: Track
          schema:
            $ref: "#/definitions/track"

  /jobs/{id}:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:772663561820:function:geolog/invocations
        httpMethod: POST
      description: Get an in-progress job
      parameters:
        - in: path
          name: id
          description: ID of the job
          required: true
          type: string
          format: string
      responses:
        200:
          description: Job
          schema:
            $ref: "#/definitions/job"
        303:
          description: Redirection to completed resource
          headers:
            location:
              description: The location of the created resource
              type: string

definitions:
  track:
    type: object
    properties:
      id:
        type: string
        format: string
      type:
        type: string
        format: string
      url:
        type: string
        format: string
        description: Location of the track
  job:
    type: object
    properties:
      id:
        type: string
        format: string
      status:
        type: string
        format: string
        description: Status of the job
