swagger: '2.0'

info:
  version: "0.0.1"
  title: geolog

consumes:
  - application/json
produces:
  - application/json
  - text/html

paths:
  # Single source of truth of the current deployment (blue / green)
  /_deployment:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {
              "statusCode" : 200
            }
        responses:
          "default":
            statusCode: "200"
            responseTemplates:
              application/json: |
                {
                  "deployment": "{{ deployment }}"
                }
      responses:
        200:
          description: Current deployment (blue / green)

  /:
    get:
      description: Request root HTML page
      responses:
        200:
          description: Content of root HTML page
          headers:
            Content-Length:
              type: string
            Content-Type:
              type: string
            ETag:
              type: string
            Last-Modified:
              type: string
            Cache-Control:
              type: string
        400:
          description: 400 response
        500:
          description: 500 response
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:eu-west-1:s3:path/{{ deployment }}.geolog.co/index.html
        passthroughBehavior: "when_no_match"
        httpMethod: "GET"
        credentials: arn:aws:iam::772663561820:role/geolog_apigateway
        responses:    
          200:
            statusCode: "200"
            responseParameters:
              method.response.header.Content-Type: "integration.response.header.Content-Type"
              method.response.header.Content-Length: "integration.response.header.Content-Length"
              method.response.header.ETag: "integration.response.header.ETag"
              method.response.header.Last-Modified: "integration.response.header.Last-Modified"
              method.response.header.Cache-Control: "integration.response.header.Cache-Control"
          4\\d{2}:
            statusCode: 400
          5\\d{2}:
            statusCode: 500

  /api/tracks:
    post:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:772663561820:function:geolog-api{{ lambdaVersion }}/invocations
        httpMethod: POST
      security:
      - sigv4: []
      description: Create a track
      responses:
        "202":
          description: Response redirecting client to job
          headers:
            location:
              description: The location of the job to query for progress of the creation of the track
              type: string
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - CORS
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {
              "statusCode" : 200
            }
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
            responseTemplates:
              application/json: |
                {}
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
  /api/tracks/{id}:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:772663561820:function:geolog-api{{ lambdaVersion }}/invocations
        httpMethod: POST
      security:
      - sigv4: []
      description: Get a track
      parameters:
        - in: path
          name: id
          description: ID of the track
          required: true
          type: string
          format: string
      responses:
        200:
          description: Track
          schema:
            $ref: "#/definitions/track"
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      parameters:
        - in: path
          name: id
          description: ID of the track
          required: true
          type: string
          format: string
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - CORS
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {
              "statusCode" : 200
            }
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
            responseTemplates:
              application/json: |
                {}
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
  /api/jobs/{id}:
    get:
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:772663561820:function:geolog-api{{ lambdaVersion }}/invocations
        httpMethod: POST
      security:
      - sigv4: []
      description: Get an in-progress job
      parameters:
        - in: path
          name: id
          description: ID of the job
          required: true
          type: string
          format: string
      responses:
        200:
          description: Job
          schema:
            $ref: "#/definitions/job"
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
        303:
          description: Redirection to completed resource
          headers:
            location:
              description: The location of the created resource
              type: string
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    options:
      summary: CORS support
      parameters:
        - in: path
          name: id
          description: ID of the track
          required: true
          type: string
          format: string
      description: |
        Enable CORS by returning correct headers
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - CORS
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {
              "statusCode" : 200
            }
        responses:
          "200":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
            responseTemplates:
              application/json: |
                {}
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
securityDefinitions:
  sigv4:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "awsSigv4"

definitions:
  track:
    type: object
    properties:
      id:
        type: string
        format: string
      type:
        type: string
        format: string
      url:
        type: string
        format: string
        description: Location of the track
  job:
    type: object
    properties:
      id:
        type: string
        format: string
      status:
        type: string
        format: string
        description: Status of the job
